# default rules
homepage:
  url:   /:sf_culture
  #gemini
  #param: { module: computer, action: index }
  #param: { module: my_login, action: index }
  param: { module: list_to_work, action: index,sf_culture:es }
  #param: { module: menu, action: index }



default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:sf_culture/:module
  param: { action: index }
  requirements: {sf_culture:(?:eu|es|en)}

default:
  url:   /:sf_culture/:module/:action/*
  requirements: {sf_culture:(?:eu|es|en)}
