default:
  http_metas:
    content-type: text/html

  metas:
    title:        Openirudi
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
